name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Run Go Tests
      run: go test -v ./...

    - name: Run Script Tests
      run: |
        go build -o y .
        for file in tests/*.y; do
          ./y "$file"
        done
